# ░█████╗░███████╗██╗████████╗███████╗███╗░░░███╗░██████╗███████╗███████╗███████╗███████╗░█████╗░████████╗░██████╗
# ██╔══██╗██╔════╝██║╚══██╔══╝██╔════╝████╗░████║██╔════╝██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗╚══██╔══╝██╔════╝
# ███████║█████╗░░██║░░░██║░░░█████╗░░██╔████╔██║╚█████╗░█████╗░░█████╗░░█████╗░░█████╗░░██║░░╚═╝░░░██║░░░╚█████╗░
# ██╔══██║██╔══╝░░██║░░░██║░░░██╔══╝░░██║╚██╔╝██║░╚═══██╗██╔══╝░░██╔══╝░░██╔══╝░░██╔══╝░░██║░░██╗░░░██║░░░░╚═══██╗
# ██║░░██║██║░░░░░██║░░░██║░░░███████╗██║░╚═╝░██║██████╔╝███████╗██║░░░░░██║░░░░░███████╗╚█████╔╝░░░██║░░░██████╔╝
# ╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝╚═╝░░░░░╚═╝░░░░░╚══════╝░╚════╝░░░░╚═╝░░░╚═════╝░
#
# Автор: anton_flame (ТГК: https://t.me/anton_flame_coder)

# Настройки плагина
settings:
  # Формат вывода информации об эффекте при использовании команды /itemseffects info
  effect-info-format: "&6%effect_type% &f(&6%effect_display_name%&f): &6%effect_level% уровень &f- &6%effect_level_price% %effect_economy_display_name%"
  # Формат вывода эффекта в описании предмета
  effect-in-lore-format: "&6%effect_type% %effect_level%"

  # Настройка эффектов (можно добавлять любые эффекты)
  effects:
    # Тип эффекта
    INCREASE_DAMAGE:
      # Название эффекта, которое будет отображаться в игре
      display-name: "Сила"
      # Уровни эффектов и их стоимость
      levels:
        # Уровень эффекта
        1:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 100

        # Уровень эффекта
        2:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 200

        # Уровень эффекта
        3:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 300

    # Тип эффекта
    SPEED:
      # Название эффекта, которое будет отображаться в игре
      display-name: "Скорость"
      # Уровни эффектов и их стоимость
      levels:
        # Уровень эффекта
        1:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 70

        # Уровень эффекта
        2:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 100

        # Уровень эффекта
        3:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 150

    # Тип эффекта
    FIRE_RESISTANCE:
      # Название эффекта, которое будет отображаться в игре
      display-name: "Огнестойкость"
      # Уровни эффектов и их стоимость
      levels:
        # Уровень эффекта
        1:
          # Вид экономики (PlayerPoints или Vault)
          economy: "Vault"
          # Название экономики
          economy-display-name: "монет"
          # Стоимость
          price: 1000

    # Тип эффекта
    DAMAGE_RESISTANCE:
      # Название эффекта, которое будет отображаться в игре
      display-name: "Сопротивление"
      # Уровни эффектов и их стоимость
      levels:
        # Уровень эффекта
        1:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 200

        # Уровень эффекта
        2:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 350

        # Уровень эффекта
        3:
          # Вид экономики (PlayerPoints или Vault)
          economy: "PlayerPoints"
          # Название экономики
          economy-display-name: "поинтов"
          # Стоимость
          price: 500

messages:
  # Сообщение при недостатке прав
  no-permission: "&cУ Вас недостаточно прав!"
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Хелп-сообщение для администраторов
  admin-help:
    - ""
    - "&fПомощь по плагину &6AFItemsEffects&f:"
    - "&6/afitemseffects reload &f- перезагрузить конфигурацию"
    - ""

  # Сообщение при использовании команды не игроком
  player-only: "&cЭта команда доступна только для игроков!"
  # Сообщение при отсутствии предмета в руке
  havent-item: "&cУ Вас нет предмета в руке!"
  # Сообщение при вводе некорректного типа эффекта
  incorrect-effect: "&cВы ввели некорректный тип эффекта!"
  # Сообщение при вводе некорректного уровня эффекта
  incorrect-level: "&cВы ввели некорректный уровень эффекта!"
  # Сообщение при вводе уровня эффекта, который выше максимального
  high-effect-level: "&cВведенный уровень эффекта выше максимального!"
  # Сообщение при добавлении эффекта на предмет, который уже добавлен с более высоким уровнем
  high-effect-already-added: "&cЭффект с более высоким уровнем уже добавлен!"
  # Сообщение при добавлении эффекта на предмет
  effect-added: "&fЭффект &6%effect% &fдобавлен на предмет!"
  # Сообщение при добавлении эффекта на предмет, который уже добавлен
  effect-already-added: "&cЭффект %effect% уже добавлен на предмет!"
  # Сообщение при нехватке валюты для добавления эффекта
  not-enough-currency: "&cУ Вас недостаточно валюты для добавления эффекта!"
  # Сообщение при отсутствии эффекта на предмете
  effect-not-found: "&cЭффект %effect% не найден на предмете!"
  # Сообщение при отсутствии эффектов на предмете
  no-effects: "&cНа предмете нет эффектов!"
  # Сообщение при удалении определенного эффекта
  effect-removed: "&fЭффект &6%effect% &fудален с предмета!"
  # Сообщение при удалении всех эффектов с предмета
  all-effects-removed: "&fВсе эффекты удалены с предмета!"
  # Сообщение с информацией об эффектах
  effects-info:
    - ""
    - "&fИнформация об эффектах:"
    - "&6%effects%"
    - ""
  # Хелп-сообщение для игроков
  player-help:
    - ""
    - "&fПомощь по командам:"
    - "&6/itemseffects add <название> <уровень> &f- добавить эффект на предмет в главной руке"
    - "&6/itemseffects remove <название> &f- снять определенный эффект с предмета в главной руке"
    - "&6/itemseffects remove all &f- снять все эффекты с предмета в главной руке"
    - "&6/itemseffects info &f- информация об эффектах"
    - ""